/**
 * `environment.names` — configuration for a scoped name, when it needs any (NAMES.md §3–§5).
 *
 * `scope.ts` says what a name's IDENTITY is: the pair `(name, scope)`. This module says what the
 * identity is CONFIGURED with and what TYPE it has, and both are questions about the whole tree
 * rather than about one state, which is why they are answered by a table the loader fills during its
 * walk and closes after it:
 *
 *  - **configuration** arrives from several writers — the entry that scopes the name, a descendant's
 *    `{ "$in": … }` contribution, the plain keys beside a use's `$ref` — and a sibling must see what
 *    another sibling contributed. Collecting first and merging once is what makes that order-free;
 *    resolving a use as the walk reached it would make a name's configuration depend on which child
 *    happened to be declared first.
 *  - **the type** is generated by the name itself: whichever position first binds it says what it is,
 *    and every later bind has to agree. The complaint belongs to the bind that disagrees, because
 *    that is the line an author has to change — the definition did nothing wrong by being first.
 *
 * What is deliberately absent is a lookup. A use is normalized where it is WRITTEN, to the concrete
 * state that scopes it, so by the time anything reads this table it is keyed by identity and nothing
 * walks scopes at run time.
 */
import type { JsonValue } from "@declarative-ai/exec";
import { mergeJson } from "./merge.js";
import { anchorScope, type ScopeLink } from "./scope.js";

/** A `names` entry as it travels down the environment chain: its block, stamped with its scope. */
export type NameEntry = { readonly $in: string } & Readonly<Record<string, JsonValue>>;

/** The `names` block of a merged environment — nearest entry wins WHOLE (NAMES.md §4). */
export type VisibleNames = Readonly<Record<string, NameEntry>>;

/** What a position takes a name AS. A provider position creates the value; `value` reads the entry. */
export type NameKind = "session" | "workspace" | "value";

/** Where something was written, for a complaint. */
export interface NameSite {
  /** The state, by the id it loads under. */
  state: string;
  path: string;
}

function isRecord(value: unknown): value is Record<string, JsonValue> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

/** The plain keys of a block — what configures, with the `$`-keys that instruct taken off. */
export function payloadOf(block: Readonly<Record<string, JsonValue>>): Record<string, JsonValue> {
  const out: Record<string, JsonValue> = {};
  for (const [key, value] of Object.entries(block)) {
    // `$any` and `$pick` stay: they ARE the entry's value, not an instruction about where it lives.
    if (key.startsWith("$") && key !== "$any" && key !== "$pick") continue;
    out[key] = value;
  }
  return out;
}

/**
 * One spelling per VALUE, whatever order its keys were written in — what "the same configuration"
 * is compared by. Key order carries no meaning anywhere in the format (REFERENCES.md §4.1: the
 * snapshot hash sorts keys), so two writers who agree must not be told they disagree.
 */
function canonical(value: JsonValue | undefined): string {
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  if (isRecord(value)) {
    return `{${Object.keys(value)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonical(value[key])}`)
      .join(",")}}`;
  }
  return JSON.stringify(value) ?? "null";
}

/** The `$`-keys an entry may carry. */
const ENTRY_KEYS: ReadonlySet<string> = new Set(["$ref", "$in", "$any", "$pick"]);

/**
 * Canonicalize one state's OWN `names` block, at the place it was written.
 *
 * Three things an entry can be (NAMES.md §4):
 *
 *  - an entry with no `$`-key is a NEW name scoped at the writer, configured only by its own block.
 *    It does not merge with an enclosing entry of the same name; that is what makes `names` the one
 *    key in `environment` where the nearest entry wins whole;
 *  - `{ "$ref": "<name>", … }` is the same, with the ENCLOSING entry's block pasted in under its own
 *    keys. Inside an entry its own name means the enclosing one, so this is not a cycle; and it is
 *    templating, like every transclusion — the block is copied here and nothing links the two after.
 *    Done here rather than in expansion because this is where the enclosing blocks are in hand;
 *  - an entry with `$in` CONTRIBUTES: it is the ancestor's name, with this block added to it. It
 *    still travels down the chain stamped with the ancestor's scope, so this state's own uses and its
 *    descendants' resolve to the ancestor's identity rather than to a private one.
 */
export function normalizeNames(
  authored: unknown,
  writer: ScopeLink,
  ancestry: readonly ScopeLink[],
  /** The entries ENCLOSING this block — what a `$ref` inside an entry pastes from. */
  enclosing: VisibleNames,
  table: NameTable,
  where: string,
): { names: Record<string, NameEntry> } | { error: { path: string; message: string } } {
  if (!isRecord(authored)) return { error: { path: where, message: "names must be a map of name → configuration block" } };
  const names: Record<string, NameEntry> = {};
  for (const [name, block] of Object.entries(authored)) {
    const path = `${where}.${name}`;
    if (name === "" || name.startsWith("$") || name.startsWith("#")) {
      return { error: { path, message: `'${name}' cannot be a name — a leading '$' is a reference and a leading '#' is reserved for keys the engine mints` } };
    }
    if (!isRecord(block)) {
      return { error: { path, message: `a name's entry is a configuration block — write {} for a name that needs none, got ${JSON.stringify(block)}` } };
    }
    const stray = Object.keys(block).find((key) => key.startsWith("$") && !ENTRY_KEYS.has(key));
    if (stray !== undefined) {
      return { error: { path, message: `'${stray}' means nothing on a names entry — an entry takes '$in' (contribute to an enclosing scope), '$ref' (paste the enclosing entry), '$any' and '$pick'` } };
    }
    let payload = payloadOf(block);
    if (block.$ref !== undefined) {
      const pasted = typeof block.$ref === "string" ? enclosing[block.$ref] : undefined;
      if (pasted === undefined) {
        return {
          error: {
            path,
            message: `inside an entry, '${String(block.$ref)}' means the ENCLOSING '${String(block.$ref)}', and no enclosing scope declares one — write the block out, or reference a file ('$/…')`,
          },
        };
      }
      payload = mergeJson(payloadOf(pasted), payload);
    }
    const redirect = block.$in;
    if (redirect !== undefined && (typeof redirect !== "string" || redirect === "")) {
      return { error: { path, message: "'$in' must name an ancestor state, or one of parent, global" } };
    }
    const scope = anchorScope(redirect as string | undefined, writer, ancestry, `name '${name}'`);
    if ("error" in scope) return { error: { path, message: scope.error } };
    // A ROLE is declared whole, where it is scoped. Its alternatives are lowered from the entry that
    // wrote them and every use reads them off that entry, so a descendant cannot add to the list —
    // it scopes a role of its own, pasting the enclosing one if it wants it (`{ "$ref": … }`).
    if (redirect !== undefined && (payload.$any !== undefined || payload.$pick !== undefined)) {
      return { error: { path, message: `'${name}' contributes '$any'/'$pick' to an enclosing scope — alternatives are declared where the role is scoped. Scope a role here (drop '$in'), pasting the enclosing one with { "$ref": "${name}" } if it should start from it` } };
    }
    table.configure(name, scope.id, payload, { state: writer.id, path });
    names[name] = { ...payload, $in: scope.id };
  }
  return { names };
}

interface Identity {
  name: string;
  scope: string;
  blocks: Array<{ block: Record<string, JsonValue>; site: NameSite }>;
  kind?: { kind: NameKind; site: NameSite };
}

/** The first place an identity was put into a position — where its TYPE is answerable for (NAMES.md §5). */
export interface NameBind extends NameSite {
  name: string;
  /** The state that scopes the identity. */
  in: string;
  kind: NameKind;
}

/** One authoring complaint, against the state and path an author has to change. */
export interface NameComplaint extends NameSite {
  message: string;
}

const describeKind = (kind: NameKind): string => (kind === "value" ? "a value" : `a ${kind}`);

/** Everything the tree said about its names, keyed by identity. */
export class NameTable {
  private readonly identities = new Map<string, Identity>();
  private readonly complaints: NameComplaint[] = [];

  private identity(name: string, scope: string): Identity {
    const key = JSON.stringify([scope, name]);
    let found = this.identities.get(key);
    if (found === undefined) {
      found = { name, scope, blocks: [] };
      this.identities.set(key, found);
    }
    return found;
  }

  /** Add configuration to an identity — from its entry, a contribution, or a use's override keys. */
  configure(name: string, scope: string, block: Record<string, JsonValue>, site: NameSite): void {
    const identity = this.identity(name, scope);
    if (Object.keys(block).length > 0) identity.blocks.push({ block, site });
  }

  /**
   * The alternatives of a ROLE — an identity whose entry holds `$any` — or `undefined` for any other
   * name. Asked of the table rather than of the entries visible at a use, because `$in` can reach
   * past a nearer entry of the same name, and the identity is what the use resolved to, not what
   * happened to be nearest. Answerable during the walk: a scope is the writer or an ancestor of it,
   * whose entries were collected before any descendant was reached, and a contribution cannot carry
   * alternatives.
   */
  roleOf(name: string, scope: string): { $any: JsonValue[]; $pick?: JsonValue } | undefined {
    for (const { block } of this.identities.get(JSON.stringify([scope, name]))?.blocks ?? []) {
      if (Array.isArray(block.$any)) return { $any: block.$any, ...(block.$pick !== undefined ? { $pick: block.$pick } : {}) };
    }
    return undefined;
  }

  /**
   * Record that a position took this identity AS something (NAMES.md §5).
   *
   * One name is one type: `impl` cannot be a workspace in one place and a session in another. The
   * first bind generates the type and a later one that disagrees is refused where IT is written.
   */
  bind(name: string, scope: string, kind: NameKind, site: NameSite): void {
    const identity = this.identity(name, scope);
    if (identity.kind === undefined) {
      identity.kind = { kind, site };
      return;
    }
    if (identity.kind.kind === kind) return;
    const first = identity.kind.site;
    this.complaints.push({
      ...site,
      message: `'${name}' is ${describeKind(identity.kind.kind)} (bound at ${first.state}: ${first.path}) and cannot also be ${describeKind(kind)} here — one name is one type; use a second name`,
    });
  }

  /**
   * Close the table: every identity's merged configuration, by scoping state, and what went wrong.
   *
   * The merge is per key, deep for maps — the environment's algebra (REFERENCES.md §4.1) — but unlike
   * that merge it has no notion of "nearer": the writers of one identity are peers. So two of them
   * setting one key to different values is not an override, it is a disagreement, and it is reported
   * rather than resolved by whichever the walk reached last.
   */
  finish(): { configs: Map<string, Record<string, JsonValue>>; complaints: NameComplaint[]; binds: NameBind[] } {
    const configs = new Map<string, Record<string, JsonValue>>();
    const complaints = [...this.complaints];
    const binds: NameBind[] = [];
    for (const identity of this.identities.values()) {
      if (identity.kind !== undefined) binds.push({ ...identity.kind.site, name: identity.name, in: identity.scope, kind: identity.kind.kind });
      const merged: Record<string, JsonValue> = {};
      const setBy = new Map<string, NameSite>();
      const mergeInto = (into: Record<string, JsonValue>, block: Record<string, JsonValue>, site: NameSite, prefix: string): void => {
        for (const [key, value] of Object.entries(block)) {
          if (key === "__proto__") continue;
          const at = prefix === "" ? key : `${prefix}.${key}`;
          const prior = into[key];
          if (isRecord(prior) && isRecord(value)) {
            mergeInto(prior, value, site, at);
            continue;
          }
          if (prior !== undefined && canonical(prior) !== canonical(value)) {
            // A key set as part of a whole sub-block was recorded under that block's path.
            let owner = at;
            while (!setBy.has(owner) && owner.includes(".")) owner = owner.slice(0, owner.lastIndexOf("."));
            const other = setBy.get(owner) ?? site;
            complaints.push({
              ...site,
              message: `'${identity.name}' is given '${at}': ${JSON.stringify(value)} here and ${JSON.stringify(prior)} at ${other.state}: ${other.path} — one identity has one configuration. Scope a new '${identity.name}' here (an entry without '$in'), or make the two agree`,
            });
            continue;
          }
          into[key] = isRecord(value) ? (JSON.parse(JSON.stringify(value)) as JsonValue) : value;
          setBy.set(at, site);
        }
      };
      for (const { block, site } of identity.blocks) mergeInto(merged, block, site, "");
      const byName = configs.get(identity.scope) ?? {};
      byName[identity.name] = merged;
      configs.set(identity.scope, byName);
    }
    return { configs, complaints, binds };
  }
}
