/**
 * Snapshot generator for the model catalog. Run via `npm run update:model-info`.
 *
 * Runs the provider catalog sources (`model-catalog-source.ts`) against the LIVE endpoints — OpenRouter's
 * public model list always, and Anthropic's `/v1/models` when `ANTHROPIC_API_KEY` is set — and writes the
 * merged rows to `src/model-catalog-data.generated.ts` as a strongly-typed `as const` tuple,
 * `GENERATED_MODELS`, which is the runtime's first-launch and offline seed (`DEFAULT_MODELS`). A client
 * refreshes its own table from the same sources at runtime (JaiRA decision 0009); this only decides what
 * a fresh install starts with.
 *
 * It starts from the CURRENT snapshot rather than from nothing, so a source that is down — or a key that
 * is absent — leaves the rows it would have written as they were instead of dropping them.
 *
 * This is a manual, lockfile-style refresh: the output is committed and reviewed. It hits the network, so
 * it's kept OUT of the normal build/test path.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { DEFAULT_MODELS, keyForModel, ModelInfo, type ModelInfoInterface } from "../src/model-catalog";
import { makeAnthropicModelsSource, makeOpenRouterSources, refreshModelCatalog, type CatalogSource, type FetchText } from "../src/model-catalog-source";

const OUTPUT_PATH = fileURLToPath(new URL("../src/model-catalog-data.generated.ts", import.meta.url));

/** Fetch a URL's body as text (the injected transport the pure refresh core needs). */
const fetchText: FetchText = async (url, init) => {
  const res = await fetch(url, { headers: { "user-agent": "declarative-ai model-info updater", ...init?.headers } });
  if (!res.ok) throw new Error(`fetch ${url} → HTTP ${res.status}`);
  return res.text();
};

/** Serialize the rows into the generated `.ts` module: JSON-shaped data + `as const satisfies` so the
 *  literal keys survive AND every row is validated against `ModelInfoInterface` at compile time. */
function renderModule(rows: ModelInfoInterface[]): string {
  const data = JSON.stringify(rows, null, 2);
  return (
    `// AUTO-GENERATED by \`npm run update:model-info\` (packages/llm/scripts/updateModelInfo.ts).\n` +
    `// Do NOT edit by hand — re-run the generator to refresh. Snapshot of the live provider catalogs\n` +
    `// (OpenRouter's model list and its native mirrors; Anthropic's /v1/models when a key was set).\n` +
    `import type { ModelInfoInterface } from "./model-catalog.js";\n\n` +
    `export const GENERATED_MODELS = ${data} as const satisfies readonly ModelInfoInterface[];\n`
  );
}

async function main(): Promise<void> {
  const table = new ModelInfo(DEFAULT_MODELS.map((row) => ({ ...row })));
  const sources: CatalogSource[] = [...makeOpenRouterSources(fetchText)];
  const key = process.env["ANTHROPIC_API_KEY"];
  if (key !== undefined && key.length > 0) sources.push(makeAnthropicModelsSource(fetchText, key));
  else console.log("  ANTHROPIC_API_KEY unset: the anthropic rows keep their OpenRouter mirror's capabilities");

  const report = await refreshModelCatalog({ sources, table, minRows: 1 });
  for (const s of report.bySource) {
    const status = s.skipped ? `SKIPPED (${s.error ?? s.problems?.join("; ") ?? "validation"})` : `applied ${s.applied}/${s.fetched}`;
    console.log(`  ${s.name}: ${status}`);
  }

  // Stable order (by `${route}/${model}` key) so the committed file diffs cleanly across runs.
  const rows = table.list().sort((a, b) => keyForModel(a).localeCompare(keyForModel(b)));
  writeFileSync(OUTPUT_PATH, renderModule(rows), "utf8");
  console.log(`Wrote ${rows.length} models → ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
