/**
 * Snapshot generator for the model catalog. Run via `npm run update:model-info`.
 *
 * Runs the model refresh/update functions (`model-catalog-source.ts`) against the LIVE sources — the
 * Anthropic docs pricing page + the OpenRouter models API — on top of the hand-maintained core seed
 * ({@link CORE_SEED_MODELS}), then writes the resulting rows to `src/model-catalog-data.generated.ts` as a
 * strongly-typed `as const` tuple. That generated module is imported by `model-catalog.ts` as
 * `DEFAULT_MODELS`, so `new ModelInfo(DEFAULT_MODELS)` gets compile-time-checked `${route}/${model}` keys.
 *
 * This is a manual, lockfile-style refresh: the output is committed and reviewed. It hits the network,
 * so it's kept OUT of the normal build/test path. A source that fails to fetch/parse/validate is skipped
 * (the refresh orchestrator keeps the existing rows), so a transient outage degrades to the core seed for
 * that source rather than corrupting the snapshot.
 *
 * Flags:
 *   --seed-only   Skip the network; emit just the completed core seed (deterministic; used to bootstrap
 *                 the committed file and for offline/CI regeneration).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { CORE_SEED_MODELS, keyForModel, ModelInfo, type ModelInfoInterface } from "../src/model-catalog";
import {
  completeSeedRow,
  makeAnthropicDocsSource,
  makeOpenRouterSource,
  refreshModelCatalog,
  type FetchText,
} from "../src/model-catalog-source";

const OUTPUT_PATH = fileURLToPath(new URL("../src/model-catalog-data.generated.ts", import.meta.url));

/** Fetch a URL's body as text (the injected transport the pure refresh core needs). */
const fetchText: FetchText = async (url) => {
  const res = await fetch(url, { headers: { "user-agent": "ai-exec model-info updater" } });
  if (!res.ok) throw new Error(`fetch ${url} → HTTP ${res.status}`);
  return res.text();
};

/** Serialize the rows into the generated `.ts` module: JSON-shaped data + `as const satisfies` so the
 *  literal keys survive AND every row is validated against `ModelInfoInterface` at compile time. */
function renderModule(rows: ModelInfoInterface[]): string {
  const data = JSON.stringify(rows, null, 2);
  return (
    `// AUTO-GENERATED by \`npm run update:model-info\` (packages/llm/scripts/updateModelInfo.ts).\n` +
    `// Do NOT edit by hand — re-run the generator to refresh. Snapshot of the live model catalog\n` +
    `// (Anthropic docs pricing + OpenRouter models API) over the hand-maintained core seed.\n` +
    `import type { ModelInfoInterface } from "./model-catalog";\n\n` +
    `export const GENERATED_MODELS = ${data} as const satisfies readonly ModelInfoInterface[];\n`
  );
}

async function main(): Promise<void> {
  const seedOnly = process.argv.includes("--seed-only");

  // Seed with the completed core rows so the core models are present even if a live source is down.
  const table = new ModelInfo(CORE_SEED_MODELS.map(completeSeedRow));

  if (!seedOnly) {
    const report = await refreshModelCatalog({
      sources: [makeAnthropicDocsSource(fetchText), makeOpenRouterSource(fetchText)],
      table,
      minRows: 1,
    });
    for (const s of report.bySource) {
      const status = s.skipped ? `SKIPPED (${s.error ?? s.problems?.join("; ") ?? "validation"})` : `applied ${s.applied}/${s.fetched}`;
      console.log(`  ${s.name}: ${status}`);
    }
  } else {
    console.log("  --seed-only: skipping network, emitting the completed core seed");
  }

  // Stable order (by `${route}/${model}` key) so the committed file diffs cleanly across runs.
  const rows = table.list().sort((a, b) => keyForModel(a).localeCompare(keyForModel(b)));
  writeFileSync(OUTPUT_PATH, renderModule(rows), "utf8");
  console.log(`Wrote ${rows.length} models → ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
