/**
 * The ONLY thing in `exec` that knows about money.
 *
 * An executor's job is to RUN things and aggregate what they report. Some of what it runs costs money
 * and some doesn't, and either way the cost is generated by the thing being run — a provider call
 * prices its tokens, a delegated agent bills inside its own loop. So `exec` proper never reads a cost:
 * it threads `M` through opaquely and merges it with the producer's own {@link MetricsAlgebra}.
 *
 * A layer whose JOB is money constrains `M extends BudgetMetrics` and reads it directly. The
 * constraint IS the capability: an executor whose metrics carry no cost cannot be budget-wrapped, and
 * that is a compile error rather than a silent no-op. Nothing else in this package imports this file.
 */

/**
 * What a measurement must carry for a budget-aware layer to price it.
 *
 * `costUsd` is REQUIRED. Optional, the interface would be structurally vacuous — every metrics record
 * would satisfy it and the constraint would stop meaning anything. Required, it also removes the
 * undefined-vs-zero ambiguity that three `?? 0` sites were papering over: "free" and "unknown" are
 * different claims, and `costSource` is where the second one belongs.
 */
export interface BudgetMetrics {
  /** USD this work cost. */
  costUsd: number;
  /** Where `costUsd` came from: the provider's actual charge (authoritative), our price table, or
   *  nothing better than a guess. */
  costSource: "provider" | "table" | "unknown";
  /** USD spent by children, for a composite that rolls its subtree up. `costUsd` INCLUDES this. */
  childCostUsd?: number;
}
// NB no `ledgerId` here. A metrics record says what the WORK measured; a credit-ledger row id is
// wallet bookkeeping the wrapper holds, not something the call reported. It lives on
// `BudgetReservation`, which is the thing that actually has one.

/**
 * Per-call budget RESERVATION — the engine-side interface to a metered wallet. One call's lifecycle:
 * `reserve(estimate)` BEFORE the call (atomic conditional decrement; refused when the balance can't
 * cover it), then `settle(actual)` when it returns.
 */
export interface BudgetReservation {
  /** Backing ledger row id, for audit references. */
  ledgerId?: string;
  /** Correct the reserved estimate to the call's ACTUAL cost. Idempotent. */
  settle(actualCostUsd: number): Promise<void>;
}

export interface BudgetMeter {
  /** `null` ⇒ the balance can't cover the estimate — clamp output or refuse the call. */
  reserve(estCostUsd: number): Promise<BudgetReservation | null>;
  /** Current USD headroom (balance minus outstanding reserves). */
  availableCostUsd(): Promise<number>;
  /**
   * Record spend that ALREADY happened and could not be reserved first — a delegated agent bills
   * inside its own loop, so its charge arrives as a fact rather than a request. Distinct from
   * `reserve`, which may refuse: this one cannot, because refusing does not un-spend the money. A
   * meter that omits it simply cannot represent an overspend.
   */
  debit?(actualCostUsd: number): Promise<void>;
}
